[2023-04-08T10:09:51.143+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: io_resto_casa.respond scheduled__2023-04-06T11:20:00+00:00 [queued]>
[2023-04-08T10:09:53.864+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: io_resto_casa.respond scheduled__2023-04-06T11:20:00+00:00 [queued]>
[2023-04-08T10:09:53.944+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T10:09:53.950+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 3
[2023-04-08T10:09:53.954+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-08T10:09:56.540+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): respond> on 2023-04-06 11:20:00+00:00
[2023-04-08T10:09:57.900+0000] {standard_task_runner.py:55} INFO - Started process 13448 to run task
[2023-04-08T10:09:58.916+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'io_resto_casa', 'respond', 'scheduled__2023-04-06T11:20:00+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmpmzpw49u_']
[2023-04-08T10:09:59.030+0000] {standard_task_runner.py:83} INFO - Job 264: Subtask respond
[2023-04-08T10:10:07.630+0000] {task_command.py:389} INFO - Running <TaskInstance: io_resto_casa.respond scheduled__2023-04-06T11:20:00+00:00 [running]> on host cfece00ff772
[2023-04-08T10:10:27.225+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=io_resto_casa
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2023-04-06T11:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-06T11:20:00+00:00
[2023-04-08T10:10:27.497+0000] {python.py:177} INFO - Done. Returned value was: Greet Responded Again
[2023-04-08T10:10:31.046+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=io_resto_casa, task_id=respond, execution_date=20230406T112000, start_date=20230408T100952, end_date=20230408T101031
[2023-04-08T10:10:36.938+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-08T10:10:39.079+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
