[2023-04-06T03:24:58.555+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: io_resto_casa.respond manual__2023-04-06T03:24:44.722423+00:00 [queued]>
[2023-04-06T03:24:58.569+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: io_resto_casa.respond manual__2023-04-06T03:24:44.722423+00:00 [queued]>
[2023-04-06T03:24:58.571+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T03:24:58.573+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-06T03:24:58.574+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-06T03:24:58.592+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): respond> on 2023-04-06 03:24:44.722423+00:00
[2023-04-06T03:24:58.599+0000] {standard_task_runner.py:55} INFO - Started process 643 to run task
[2023-04-06T03:24:58.603+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'io_resto_casa', 'respond', 'manual__2023-04-06T03:24:44.722423+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/ciao.py', '--cfg-path', '/tmp/tmpdu0p96tp']
[2023-04-06T03:24:58.607+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask respond
[2023-04-06T03:24:58.698+0000] {task_command.py:389} INFO - Running <TaskInstance: io_resto_casa.respond manual__2023-04-06T03:24:44.722423+00:00 [running]> on host cfece00ff772
[2023-04-06T03:24:58.787+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=io_resto_casa
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2023-04-06T03:24:44.722423+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-06T03:24:44.722423+00:00
[2023-04-06T03:24:58.791+0000] {python.py:177} INFO - Done. Returned value was: Greet Responded Again
[2023-04-06T03:24:58.818+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=io_resto_casa, task_id=respond, execution_date=20230406T032444, start_date=20230406T032458, end_date=20230406T032458
[2023-04-06T03:24:58.857+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-06T03:24:58.880+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
